# Generated by Django 4.2.19 on 2025-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('accounts_and_auditing ', 'Accounts and Auditing'), ('developer ', 'Developer')], default='partner', max_length=50),
        ),
    ]
