# Generated by Django 4.2.19 on 2025-08-05 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50, unique=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('groupId', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='inactive', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.TextField(default='')),
                ('address_line1', models.CharField(default='', max_length=255)),
                ('address_line2', models.CharField(default='', max_length=255)),
                ('address_city', models.CharField(default='', max_length=100)),
                ('address_pin', models.CharField(default='', max_length=20)),
                ('address_state', models.CharField(blank=True, default='', max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('activationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('expirationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('installationTime', models.DateField(default=django.utils.timezone.now)),
                ('billing_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type', models.CharField(default='home', max_length=50)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20)),
                ('alt_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('group_name', models.CharField(default='', max_length=100)),
                ('profile_id', models.CharField(default='', max_length=100)),
                ('profile_name', models.CharField(default='', max_length=100)),
                ('installation_address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('installation_address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('installation_address_city', models.CharField(blank=True, default='', max_length=100)),
                ('installation_address_pin', models.CharField(blank=True, default='', max_length=20)),
                ('installation_address_state', models.CharField(blank=True, default='', max_length=100)),
                ('installation_address_country', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstNumber', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, default='', max_length=100)),
                ('userNasPortId', models.CharField(default='', max_length=100)),
                ('billingType', models.CharField(default='Pay As You Go', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='StaticIpMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staticIpAddress', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('staticIpBoundMac', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBillingCycleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidthTemplateId', models.CharField(default='', max_length=100)),
                ('bandwidthTemplateName', models.CharField(default='', max_length=100)),
                ('bandwidthTemplateMikrotik', models.CharField(default='', max_length=255)),
                ('bandwidthTemplateUpload', models.BigIntegerField(default=0)),
                ('bandwidthTemplateDownload', models.BigIntegerField(default=0)),
                ('billingResetType', models.CharField(default='', max_length=50)),
                ('billingStartDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('billingEndDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploadDataUsage', models.BigIntegerField(default=0)),
                ('downloadDataUsage', models.BigIntegerField(default=0)),
                ('totalDataUsage', models.BigIntegerField(default=0)),
                ('usedBandwidthQuota', models.BigIntegerField(default=0)),
                ('totalBandwidthQuota', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastOrderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastInvoiceDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastPaymentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusId', models.CharField(default='unpaid', max_length=50)),
                ('totalOwed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetimeRevenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
    ]
