# Generated by Django 4.2.19 on 2025-08-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0011_remove_category_language_remove_radio_created_at_and_more'),
        ('customer', '0003_remove_customer_device_id_remove_customer_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='iptvengine.tariff'),
        ),
    ]
