# Generated by Django 4.2.19 on 2025-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='iptv_activation_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
