# Generated by Django 4.2.19 on 2025-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='code',
            field=models.CharField(default='default_code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, default='default_value', max_length=200, null=True),
        ),
    ]
