# Generated by Django 4.2.19 on 2025-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_setting_code_alter_setting_name_alter_setting_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RemoveField(
            model_name='setting',
            name='code',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='max_devices',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of devices allowed per customer'),
        ),
    ]
