# Generated by Django 4.2.19 on 2025-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_setting_options_remove_setting_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
