# Generated by Django 4.2.19 on 2025-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_verificationcode_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
