# Generated by Django 4.2.19 on 2025-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_device_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
