# Generated by Django 4.2.19 on 2025-09-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='New Profile', max_length=50)),
                ('profile_type', models.CharField(choices=[('adult', 'Adult'), ('kids', 'Kids')], default='adult', max_length=20)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='profile_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='customer.customer')),
            ],
        ),
    ]
