# Generated by Django 4.2.19 on 2025-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
