# Generated by Django 4.2.19 on 2025-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_profile_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Full URL to avatar image', max_length=500, null=True),
        ),
    ]
