# Generated by Django 4.2.19 on 2025-09-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(db_index=True, default='New Profile', max_length=50, unique=True),
        ),
    ]
