# Generated by Django 4.2.19 on 2025-09-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('customer', 'profile_name'), name='unique_profile_per_customer'),
        ),
    ]
