# Generated by Django 4.2.19 on 2025-09-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0012_delete_device'),
        ('customer', '0023_watchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_channels', to='iptvengine.channel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_channels', to='customer.customer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_channels', to='customer.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'channel')},
            },
        ),
    ]
