# Generated by Django 4.2.19 on 2025-09-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0012_delete_device'),
        ('customer', '0024_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='iptvengine.channel'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to='customer.profile'),
        ),
    ]
