# Generated by Django 4.2.19 on 2025-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LauncherWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_video', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, default='launcher/default.jpg', null=True, upload_to='launcher/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
