# Generated by Django 4.2.19 on 2025-09-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigLiveTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Channel', max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('languageId', models.CharField(default='en', max_length=10)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('drmType', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('licenceUrl', models.URLField(blank=True, default=None, null=True)),
                ('drmHeaders', models.JSONField(blank=True, default=dict, null=True)),
                ('drmLicenceHeaders', models.JSONField(blank=True, default=dict, null=True)),
                ('isPremium', models.BooleanField(default=False)),
                ('isTrailer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuickNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Navigation', max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quicknav/images/')),
                ('backdrop', models.URLField(blank=True, default='', null=True)),
                ('suggestedContentUrl', models.URLField(blank=True, default='', null=True)),
                ('isTrailer', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('LIVETV', 'Live TV'), ('VOD', 'Video on Demand'), ('FM', 'FM Radio'), ('SETTINGS', 'Settings'), ('PROFILE', 'Profile'), ('APPS', 'Apps')], default='LIVETV', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('QuickNavigation', 'Quick Navigation'), ('SEARCH', 'Search Suggestions'), ('LIVE_TV', 'Popular Live TV Channels')], max_length=100, unique=True)),
                ('biglivetv_channels', models.ManyToManyField(blank=True, to='launcher.biglivetv')),
                ('quick_navigation', models.ManyToManyField(blank=True, to='launcher.quicknavigation')),
                ('search_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='launcher.searchsuggestion')),
            ],
        ),
    ]
