# Generated by Django 4.2.19 on 2025-09-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0002_biglivetv_quicknavigation_searchsuggestion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknavigation',
            name='image',
        ),
        migrations.AlterField(
            model_name='quicknavigation',
            name='backdrop',
            field=models.ImageField(blank=True, default='quicknav/backdrops/default_backdrop.jpg', null=True, upload_to='quicknav/backdrops/'),
        ),
        migrations.AlterField(
            model_name='quicknavigation',
            name='description',
            field=models.TextField(blank=True, default='No description available', null=True),
        ),
        migrations.AlterField(
            model_name='quicknavigation',
            name='suggestedContentUrl',
            field=models.URLField(blank=True, default='http://example.com/default_video.m3u8', null=True),
        ),
    ]
