# Generated by Django 4.2.19 on 2025-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0003_remove_quicknavigation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='New Category', max_length=200, unique=True),
        ),
    ]
