# Generated by Django 4.2.19 on 2025-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('QUICK_NAV', 'Quick Navigation'), ('SEARCH', 'Search Suggestions'), ('LIVE_TV', 'Popular Live TV Channels')], default='QUICK_NAV', max_length=20),
        ),
    ]
