# Generated by Django 4.2.19 on 2025-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0012_delete_device'),
        ('launcher', '0005_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='genres', to='iptvengine.channel')),
            ],
            options={
                'verbose_name': 'Channel Genre',
                'verbose_name_plural': 'Channel Genres',
                'ordering': ['order', 'name'],
            },
        ),
    ]
