# Generated by Django 4.2.19 on 2025-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0006_channelgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgenre',
            name='type',
            field=models.CharField(choices=[('BigLiveTv', 'Big Live TV'), ('LiveTv', 'Live TV')], default='LiveTv', max_length=20),
        ),
    ]
