# Generated by Django 4.2.19 on 2025-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0007_channelgenre_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='biglivetv_channels',
        ),
        migrations.DeleteModel(
            name='BigLiveTv',
        ),
    ]
