# Generated by Django 4.2.19 on 2025-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0008_remove_category_biglivetv_channels_delete_biglivetv'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='channel_genres',
            field=models.ManyToManyField(blank=True, to='launcher.channelgenre'),
        ),
    ]
