# Generated by Django 4.2.19 on 2025-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0009_category_channel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('QUICK_NAV', 'Quick Navigation'), ('SEARCH', 'Search Suggestions'), ('LIVE_TV', 'Popular Live TV Channels'), ('UserLiveTvHistory', 'Continue Watching')], default='QUICK_NAV', max_length=20),
        ),
    ]
