# Generated by Django 4.2.19 on 2025-09-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0011_alter_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
