# Generated by Django 4.2.19 on 2025-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0012_category_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknavigation',
            name='image',
            field=models.ImageField(blank=True, default='quicknav/images/default_image.jpg', null=True, upload_to='quicknav/images/'),
        ),
    ]
