# Generated by Django 4.2.19 on 2025-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0013_quicknavigation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('QUICK_NAV', 'Quick Navigation'), ('SEARCH', 'Search Suggestions'), ('LIVE_TV', 'Popular Live TV Channels'), ('FAVORITE', 'Continue favorites'), ('WATCHLIST', 'Continue Watching'), ('STATIC_MOVIES', 'Static Movies')], default='QUICK_NAV', max_length=20),
        ),
    ]
