# Generated by Django 4.2.19 on 2025-10-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0014_alter_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknavigation',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
