# Generated by Django 4.2.19 on 2025-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launcher', '0015_quicknavigation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknavigation',
            name='image',
        ),
        migrations.AddField(
            model_name='quicknavigation',
            name='focusedImage',
            field=models.ImageField(blank=True, default='quicknav/images/unfocused/default_unfocused.jpg', null=True, upload_to='quicknav/images/unfocused/'),
        ),
        migrations.AddField(
            model_name='quicknavigation',
            name='unfocusedImage',
            field=models.ImageField(blank=True, default='quicknav/images/unfocused/default_unfocused.jpg', null=True, upload_to='quicknav/images/unfocused/'),
        ),
    ]
