# Generated by Django 4.2.19 on 2025-08-26 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('is_payed', models.BooleanField(db_index=True, default=False)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=8)),
                ('logo', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('favorite', models.BooleanField(db_index=True, default=False)),
                ('timeshift', models.PositiveIntegerField(default=0)),
                ('adult', models.BooleanField(db_index=True, default=False)),
                ('show_price', models.BooleanField(default=False)),
                ('ppv', models.BooleanField(default=False)),
                ('ppv_link', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('drm_type', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='iptvengine.category')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='iptvengine.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='', max_length=200, unique=True)),
                ('customer_id', models.CharField(db_index=True, default='', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(db_index=True, default='', max_length=200)),
                ('name', models.CharField(db_index=True, default='', max_length=200)),
                ('source_url', models.URLField(db_index=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='iptvengine.channelgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_url', models.URLField(db_index=True, default='', max_length=500)),
                ('header_key', models.CharField(db_index=True, default='', max_length=100)),
                ('header_value', models.CharField(db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='iptvengine.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='iptvengine__name_9fc8f6_idx'), models.Index(fields=['display_order'], name='iptvengine__display_602f11_idx'), models.Index(fields=['created_at'], name='iptvengine__created_aeb7cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelSourceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, default='', max_length=500)),
                ('header_key', models.CharField(db_index=True, default='', max_length=100)),
                ('header_value', models.CharField(db_index=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='iptvengine.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='iptvengine.language'),
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='iptvengine.language'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='iptvengine__name_116e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='iptvengine__created_007041_idx'),
        ),
    ]
