# Generated by Django 4.2.19 on 2025-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='iptvengine__name_116e7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='iptvengine__created_007041_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='iptvengine__name_9fc8f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='iptvengine__display_602f11_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='iptvengine__created_aeb7cb_idx',
        ),
        migrations.RemoveField(
            model_name='channelgroup',
            name='channel',
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='groups', to='iptvengine.channel'),
        ),
    ]
