# Generated by Django 4.2.19 on 2025-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0002_alter_category_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='channel_group',
        ),
        migrations.AddField(
            model_name='tariff',
            name='channel_groups',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='iptvengine.channelgroup'),
        ),
    ]
