# Generated by Django 4.2.19 on 2025-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0003_remove_tariff_channel_group_tariff_channel_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroup',
            name='license_headers',
            field=models.ManyToManyField(blank=True, related_name='channels', to='iptvengine.licenseheader'),
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='source_headers',
            field=models.ManyToManyField(blank=True, related_name='channels', to='iptvengine.channelsourceheader'),
        ),
    ]
