# Generated by Django 4.2.19 on 2025-08-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0004_channelgroup_license_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radios', to='iptvengine.language'),
        ),
    ]
