# Generated by Django 4.2.19 on 2025-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0005_radio_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='drm_type',
            field=models.CharField(choices=[('NONE', 'None'), ('WIDEVINE', 'Widevine'), ('FAIRPLAY', 'FairPlay'), ('PLAYREADY', 'PlayReady')], db_index=True, default='NONE', max_length=50),
        ),
    ]
