# Generated by Django 4.2.19 on 2025-08-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0006_alter_channel_drm_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsourceheader',
            name='header_key',
        ),
        migrations.RemoveField(
            model_name='channelsourceheader',
            name='header_value',
        ),
        migrations.RemoveField(
            model_name='licenseheader',
            name='header_key',
        ),
        migrations.RemoveField(
            model_name='licenseheader',
            name='header_value',
        ),
        migrations.AddField(
            model_name='channelsourceheader',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='licenseheader',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='channelsourceheader',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='iptvengine.channel'),
        ),
        migrations.AlterField(
            model_name='licenseheader',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='iptvengine.channel'),
        ),
    ]
