# Generated by Django 4.2.19 on 2025-08-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0007_remove_channelsourceheader_header_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsourceheader',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='licenseheader',
            name='headers',
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='license_headers',
            field=models.ManyToManyField(blank=True, related_name='channel_groups', to='iptvengine.licenseheader'),
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='source_headers',
            field=models.ManyToManyField(blank=True, related_name='channel_groups', to='iptvengine.channelsourceheader'),
        ),
        migrations.CreateModel(
            name='SourceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='User-Agent', max_length=255)),
                ('value', models.CharField(default='Mozilla/5.0', max_length=500)),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='iptvengine.channelsourceheader')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHeaderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='Authorization', max_length=255)),
                ('value', models.CharField(default='Bearer token_here', max_length=500)),
                ('license', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='iptvengine.licenseheader')),
            ],
        ),
    ]
