# Generated by Django 4.2.19 on 2025-08-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0008_remove_channelsourceheader_headers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseheader',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelgroup',
            name='license_headers',
        ),
        migrations.RemoveField(
            model_name='channelgroup',
            name='source_headers',
        ),
        migrations.RemoveField(
            model_name='licenseheaderitem',
            name='license',
        ),
        migrations.RemoveField(
            model_name='sourceheader',
            name='source',
        ),
        migrations.AddField(
            model_name='channel',
            name='license_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='licenseheaderitem',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_headers', to='iptvengine.channel'),
        ),
        migrations.AddField(
            model_name='sourceheader',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_headers', to='iptvengine.channel'),
        ),
        migrations.DeleteModel(
            name='ChannelSourceHeader',
        ),
        migrations.DeleteModel(
            name='LicenseHeader',
        ),
    ]
