# Generated by Django 4.2.19 on 2025-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0009_remove_licenseheader_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='channels/logos/'),
        ),
    ]
