# Generated by Django 4.2.19 on 2025-08-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0010_channel_description_alter_channel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='radio',
            name='is_fm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radio',
            name='source',
            field=models.URLField(default='http://example.com/stream', max_length=500),
        ),
        migrations.AlterField(
            model_name='radio',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radios', to='iptvengine.language'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='name',
            field=models.CharField(default='Unknown Radio', max_length=100),
        ),
    ]
