# Generated by Django 4.2.19 on 2025-08-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0011_remove_category_language_remove_radio_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
