# Generated by Django 4.2.19 on 2025-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0012_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='tvBanner',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
