# Generated by Django 4.2.19 on 2025-10-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0013_language_tvbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='tvBanner',
            new_name='tv_banner',
        ),
    ]
