# Generated by Django 4.2.19 on 2025-10-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvengine', '0014_rename_tvbanner_language_tv_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='image_url',
        ),
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages/images/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='tv_banner',
            field=models.ImageField(blank=True, null=True, upload_to='languages/banners/'),
        ),
    ]
