# Generated by Django 4.2.19 on 2025-08-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UITweaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('cosmo', 'Cosmo'), ('flatly', 'Flatly'), ('cyborg', 'Cyborg'), ('slate', 'Slate'), ('superhero', 'Superhero'), ('lux', 'Lux'), ('litera', 'Litera'), ('simplex', 'Simplex'), ('solar', 'Solar'), ('darkly', 'Darkly')], default='cosmo', max_length=50)),
                ('navbar', models.CharField(choices=[('navbar-white', 'White'), ('navbar-dark', 'Dark'), ('navbar-light', 'Light'), ('navbar-primary', 'Primary'), ('navbar-success', 'Success'), ('navbar-info', 'Info'), ('navbar-warning', 'Warning'), ('navbar-danger', 'Danger')], default='navbar-dark', max_length=50)),
                ('brand_colour', models.CharField(choices=[('navbar-white', 'White'), ('navbar-dark', 'Dark'), ('navbar-light', 'Light'), ('navbar-primary', 'Primary'), ('navbar-success', 'Success'), ('navbar-info', 'Info'), ('navbar-warning', 'Warning'), ('navbar-danger', 'Danger')], default='navbar-success', max_length=50)),
                ('sidebar', models.CharField(choices=[('sidebar-dark-primary', 'Dark Primary'), ('sidebar-dark-info', 'Dark Info'), ('sidebar-light', 'Light')], default='sidebar-dark-info', max_length=50)),
                ('accent', models.CharField(default='accent-teal', max_length=50)),
                ('navbar_small_text', models.BooleanField(default=False)),
                ('footer_small_text', models.BooleanField(default=False)),
                ('body_small_text', models.BooleanField(default=False)),
                ('brand_small_text', models.BooleanField(default=False)),
                ('no_navbar_border', models.BooleanField(default=False)),
                ('navbar_fixed', models.BooleanField(default=False)),
                ('layout_boxed', models.BooleanField(default=False)),
                ('footer_fixed', models.BooleanField(default=False)),
                ('sidebar_fixed', models.BooleanField(default=False)),
                ('sidebar_nav_small_text', models.BooleanField(default=False)),
                ('sidebar_disable_expand', models.BooleanField(default=False)),
                ('sidebar_nav_child_indent', models.BooleanField(default=False)),
                ('sidebar_nav_compact_style', models.BooleanField(default=False)),
                ('sidebar_nav_legacy_style', models.BooleanField(default=False)),
                ('sidebar_nav_flat_style', models.BooleanField(default=False)),
                ('dark_mode_theme', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jazzmin UI Tweaks',
            },
        ),
    ]
