# Generated by Django 4.2.19 on 2025-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitweaks',
            name='dark_mode_theme',
            field=models.CharField(blank=True, default='darkly', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uitweaks',
            name='navbar_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uitweaks',
            name='sidebar_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
