# Generated by Django 4.2.19 on 2025-08-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_uitweaks_dark_mode_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitweaks',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='name',
            field=models.CharField(default='theme1', max_length=100),
        ),
    ]
