# Generated by Django 4.2.19 on 2025-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_uitweaks_is_active_uitweaks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JazzminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(default='default', max_length=100)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
