# Generated by Django 4.2.19 on 2025-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_jazzminsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jazzminsettings',
            old_name='theme_name',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='custom_css',
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='custom_title',
            field=models.CharField(default='My Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='show_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
