# Generated by Django 4.2.19 on 2025-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_rename_theme_name_jazzminsettings_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitweaks',
            name='danger_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-danger', max_length=20, verbose_name='Danger Button'),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='info_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-info', max_length=20, verbose_name='Info Button'),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='primary_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-primary', max_length=20, verbose_name='Primary Button'),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='secondary_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-secondary', max_length=20, verbose_name='Secondary Button'),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='success_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-success', max_length=20, verbose_name='Success Button'),
        ),
        migrations.AddField(
            model_name='uitweaks',
            name='warning_button',
            field=models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-info', 'Info'), ('btn-warning', 'Warning'), ('btn-danger', 'Danger'), ('btn-success', 'Success')], default='btn-warning', max_length=20, verbose_name='Warning Button'),
        ),
    ]
