# Generated by Django 4.2.19 on 2025-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_uitweaks_danger_button_uitweaks_info_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jazzminsettings',
            old_name='show_sidebar',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='custom_title',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='copyright',
            field=models.CharField(default='Skylink', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='iptvengine_channel_icon',
            field=models.CharField(default='fas fa-tv', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='iptvengine_device_icon',
            field=models.CharField(default='fas fa-satellite', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='iptvengine_icon',
            field=models.CharField(default='fas fa-broadcast-tower', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='iptvengine_pack_icon',
            field=models.CharField(default='fas fa-box-open', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='iptvengine_tariff_icon',
            field=models.CharField(default='fas fa-coins', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='site_brand',
            field=models.CharField(default='Skylink', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='site_header',
            field=models.CharField(default='IPTV', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='site_title',
            field=models.CharField(default='Skylink IPTV', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='welcome_sign',
            field=models.CharField(default='Welcome to the Skylink IPTV', max_length=200),
        ),
    ]
