# Generated by Django 4.2.19 on 2025-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_rename_show_sidebar_jazzminsettings_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='iptvengine_channel_icon',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='iptvengine_device_icon',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='iptvengine_icon',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='iptvengine_pack_icon',
        ),
        migrations.RemoveField(
            model_name='jazzminsettings',
            name='iptvengine_tariff_icon',
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='default_icon_children',
            field=models.CharField(default='fas fa-arrow-circle-right', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='default_icon_parents',
            field=models.CharField(default='fas fa-chevron-circle-right', max_length=100),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='navigation_expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='related_modal_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='show_sidebar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='site_icon',
            field=models.CharField(default='images/favicon.png', max_length=255),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='jazzminsettings',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='jazzminsettings',
            name='copyright',
            field=models.CharField(default='Skylink IPTV', max_length=100),
        ),
        migrations.AlterField(
            model_name='jazzminsettings',
            name='site_brand',
            field=models.CharField(default='IPTV Engine', max_length=100),
        ),
        migrations.AlterField(
            model_name='jazzminsettings',
            name='site_title',
            field=models.CharField(default='IPTV Engine', max_length=100),
        ),
        migrations.AlterField(
            model_name='jazzminsettings',
            name='welcome_sign',
            field=models.CharField(default='Welcome to the Skylink IPTV', max_length=255),
        ),
    ]
