# Generated by Django 4.2.19 on 2025-08-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_remove_jazzminsettings_iptvengine_channel_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jazzminsettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='uitweaks',
            options={'verbose_name': 'Appearance Setting', 'verbose_name_plural': 'Appearance Settings'},
        ),
    ]
