# Generated by Django 4.2.19 on 2025-10-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, default='Untitled Movie', max_length=255, null=True)),
                ('poster', models.URLField(blank=True, default='', null=True)),
                ('backdrop', models.URLField(blank=True, default='', null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
                ('quality', models.CharField(blank=True, default='HD', max_length=50, null=True)),
                ('rating', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('isPremiumFirst', models.BooleanField(blank=True, default=False, null=True)),
                ('isPremium', models.BooleanField(blank=True, default=False, null=True)),
                ('watchingCount', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('isAdult', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('trailer', models.URLField(blank=True, default='', null=True)),
                ('isTrailer', models.BooleanField(blank=True, default=False, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.moviecategory')),
            ],
        ),
    ]
