# Generated by Django 4.2.19 on 2025-10-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecategory_category_id_alter_movie_isadult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='movies.movie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
