# Generated by Django 4.2.19 on 2025-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_intent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
