# Generated by Django 4.2.19 on 2025-10-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_intent_movie_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_intent',
            field=models.BooleanField(default=True),
        ),
    ]
