# Generated by Django 4.2.19 on 2025-08-06 10:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_remove_partner_phone_partner_active_partner_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='partner.partner'),
        ),
    ]
