# Generated by Django 4.2.19 on 2025-08-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_remove_wallettransaction_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='physical_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='visual_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
