# Generated by Django 4.2.19 on 2025-08-07 06:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_partner_physical_wallet_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='physical_wallet_balance',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='visual_wallet_balance',
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(default='PARTNER_000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(default='Unnamed Partner', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='partner.partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('operator', 'Operator')], default='distributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='partner.partner'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='remarks',
            field=models.TextField(blank=True, default='No remarks'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main Wallet'), ('offer', 'Offer Wallet'), ('virtual', 'Virtual Wallet'), ('physical', 'Physical Wallet')], default='main', max_length=10),
        ),
    ]
