# Generated by Django 4.2.19 on 2025-08-07 06:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_remove_partner_active_remove_partner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
