# Generated by Django 4.2.19 on 2025-08-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_partner_calculated_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='calculated_amount',
        ),
    ]
